### ISSUE TITLE
运行成功没报错，但是登录不进报错

### ISSUE THREAD

**Issue by icegodness** [Ikarosx/RestaurantOrder#19]
为什么我前后端运行成功都没报错，mysql数据库也连上了，但是我在登陆界面注册和登录都不行，提示network error 错误

**Comment by Ikarosx** [comment]
> 为什么我前后端运行成功都没报错，mysql数据库也连上了，但是我在登陆界面注册和登录都不行，提示network error 错误

能不能f12提供一下报错信息，查看一下哪个接口报的错，通常这个错误是请求的地址不通
